// AUTO MAINTAINED FILE: DO NOT CHANGE

export const HOME_COUNTER_PLUS_ONE = 'HOME_COUNTER_PLUS_ONE';
export const HOME_COUNTER_MINUS_ONE = 'HOME_COUNTER_MINUS_ONE';
export const HOME_RESET_COUNTER = 'HOME_RESET_COUNTER';
export const HOME_FETCH_REDDIT_REACTJS_LIST_BEGIN = 'HOME_FETCH_REDDIT_REACTJS_LIST_BEGIN';
export const HOME_FETCH_REDDIT_REACTJS_LIST_SUCCESS = 'HOME_FETCH_REDDIT_REACTJS_LIST_SUCCESS';
export const HOME_FETCH_REDDIT_REACTJS_LIST_FAILURE = 'HOME_FETCH_REDDIT_REACTJS_LIST_FAILURE';
export const HOME_FETCH_REDDIT_REACTJS_LIST_DISMISS_ERROR = 'HOME_FETCH_REDDIT_REACTJS_LIST_DISMISS_ERROR';
export const HOME_REDUX_BEGIN = 'HOME_REDUX_BEGIN';
export const HOME_REDUX_SUCCESS = 'HOME_REDUX_SUCCESS';
export const HOME_REDUX_FAILURE = 'HOME_REDUX_FAILURE';
export const HOME_REDUX_DISMISS_ERROR = 'HOME_REDUX_DISMISS_ERROR';
export const HOME_FETCH_ENVIRONMS_BEGIN = 'HOME_FETCH_ENVIRONMS_BEGIN';
export const HOME_FETCH_ENVIRONMS_SUCCESS = 'HOME_FETCH_ENVIRONMS_SUCCESS';
export const HOME_FETCH_ENVIRONMS_FAILURE = 'HOME_FETCH_ENVIRONMS_FAILURE';
export const HOME_FETCH_ENVIRONMS_DISMISS_ERROR = 'HOME_FETCH_ENVIRONMS_DISMISS_ERROR';

// user constatns
export const API_URL = 'http://192.168.0.112:8080/api'
export const HOME_ADD_ENVIRONM_BEGIN = 'HOME_ADD_ENVIRONM_BEGIN';
export const HOME_ADD_ENVIRONM_SUCCESS = 'HOME_ADD_ENVIRONM_SUCCESS';
export const HOME_ADD_ENVIRONM_FAILURE = 'HOME_ADD_ENVIRONM_FAILURE';
export const HOME_ADD_ENVIRONM_DISMISS_ERROR = 'HOME_ADD_ENVIRONM_DISMISS_ERROR';
export const HOME_FETCH_DEVICES_BEGIN = 'HOME_FETCH_DEVICES_BEGIN';
export const HOME_FETCH_DEVICES_SUCCESS = 'HOME_FETCH_DEVICES_SUCCESS';
export const HOME_FETCH_DEVICES_FAILURE = 'HOME_FETCH_DEVICES_FAILURE';
export const HOME_FETCH_DEVICES_DISMISS_ERROR = 'HOME_FETCH_DEVICES_DISMISS_ERROR';
export const HOME_ADD_DEVICE_BEGIN = 'HOME_ADD_DEVICE_BEGIN';
export const HOME_ADD_DEVICE_SUCCESS = 'HOME_ADD_DEVICE_SUCCESS';
export const HOME_ADD_DEVICE_FAILURE = 'HOME_ADD_DEVICE_FAILURE';
export const HOME_ADD_DEVICE_DISMISS_ERROR = 'HOME_ADD_DEVICE_DISMISS_ERROR';
export const HOME_ADD_SENSOR_BEGIN = 'HOME_ADD_SENSOR_BEGIN';
export const HOME_ADD_SENSOR_SUCCESS = 'HOME_ADD_SENSOR_SUCCESS';
export const HOME_ADD_SENSOR_FAILURE = 'HOME_ADD_SENSOR_FAILURE';
export const HOME_ADD_SENSOR_DISMISS_ERROR = 'HOME_ADD_SENSOR_DISMISS_ERROR';
export const HOME_FETCH_SENSORS_BEGIN = 'HOME_FETCH_SENSORS_BEGIN';
export const HOME_FETCH_SENSORS_SUCCESS = 'HOME_FETCH_SENSORS_SUCCESS';
export const HOME_FETCH_SENSORS_FAILURE = 'HOME_FETCH_SENSORS_FAILURE';
export const HOME_FETCH_SENSORS_DISMISS_ERROR = 'HOME_FETCH_SENSORS_DISMISS_ERROR';
export const HOME_SET_ACTIVE_ENTORNO = 'HOME_SET_ACTIVE_ENTORNO';
